spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tileforms
    username: tileforms
    password: tileforms
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
  jpa:
    show-sql: true

logging:
  level:
    com.tileforms: DEBUG
    org.springframework.security: DEBUG
